import type { ScrollExperience } from "./scroll-experience.js";
import type { PublicId } from "./types.js";

const asPublicId = (value: string) => value as PublicId;

export const echinopsisScrollExperience = {
  schemaVersion: "1.0",
  publicId: asPublicId("experience-echinopsis-pachanoi-scroll"),
  biologicalEntityPublicId: asPublicId("biological-entity-echinopsis-pachanoi"),
  title: "Echinopsis pachanoi",
  subtitle:
    "Una especie leída como forma, cultivo, territorio, memoria y pregunta científica.",
  modelUri: "/models/echinopsis-pachanoi-demo.glb",
  representationType: "procedural-interpretation",
  chapters: [
    {
      id: "identity",
      eyebrow: "01 · identidad",
      title: "Una columna viva",
      body: "Desplázate para girar una interpretación visual de Echinopsis pachanoi. La escena no es un ejemplar científico: es una puerta de entrada a sus capas de conocimiento.",
      layer: "identity",
      sourcePublicIds: [
        asPublicId("source-powo-echinopsis-pachanoi"),
        asPublicId("source-gbif-echinopsis-pachanoi"),
      ],
      camera: { distance: 4.9, height: 1.15, targetHeight: 1.15, fov: 38 },
      rotationTurns: 0,
      accent: "#6b8e62",
      status: "published",
    },
    {
      id: "cultivation",
      eyebrow: "02 · cultivo",
      title: "La forma también guarda clima",
      body: "La lectura de cultivo queda separada de la taxonomía: sustrato, luz, riego y propagación deben conservar región, técnica, autor y fuente.",
      layer: "cultivation",
      sourcePublicIds: [asPublicId("source-rhs-cacti-succulents-guide")],
      camera: { distance: 4.25, height: 0.9, targetHeight: 1.1, fov: 36 },
      rotationTurns: 0.8,
      accent: "#b8a26d",
      status: "published",
    },
    {
      id: "ecology",
      eyebrow: "03 · ecología",
      title: "Ecuador, Perú y las condiciones de vida",
      body: "La distribución publicada se conserva como afirmación de fuente. Una ocurrencia contemporánea no se convierte automáticamente en rango nativo.",
      layer: "ecology",
      sourcePublicIds: [asPublicId("source-powo-echinopsis-pachanoi")],
      camera: { distance: 4.65, height: 1.6, targetHeight: 1.2, fov: 40 },
      rotationTurns: 1.65,
      accent: "#8aa18b",
      status: "published",
    },
    {
      id: "material-chemistry",
      eyebrow: "04 · materia y química",
      title: "La luz no es un análisis de laboratorio",
      body: "La rugosidad, la transmisión y el color son parámetros de una interpretación material. La química y la nutrición aparecerán cuando cada medición tenga método, tejido, unidad y fuente.",
      layer: "chemistry",
      sourcePublicIds: [],
      camera: { distance: 3.8, height: 1.05, targetHeight: 1.25, fov: 34 },
      rotationTurns: 2.55,
      accent: "#d4935a",
      status: "research-pending",
    },
    {
      id: "history-culture",
      eyebrow: "05 · historia y cultura",
      title: "Los nombres tienen territorio",
      body: "San Pedro se conserva como nombre situado en fuentes y comunidades concretas. No se presenta como equivalencia cultural universal ni como una afirmación sin procedencia.",
      layer: "culture",
      sourcePublicIds: [asPublicId("source-armijos-saraguro-yachakkuna-2014")],
      camera: { distance: 4.35, height: 1.3, targetHeight: 1.05, fov: 37 },
      rotationTurns: 3.45,
      accent: "#a76e5a",
      status: "research-pending",
    },
    {
      id: "related-taxa",
      eyebrow: "06 · parientes y confundidos",
      title: "Peruvian, Bolivian y otros nombres de comercio",
      body: "Los nombres comerciales no se resolverán automáticamente como especies. La futura categoría comparará taxones, sinónimos, híbridos y cultivares con fuentes taxonómicas independientes.",
      layer: "related-taxa",
      sourcePublicIds: [],
      camera: { distance: 4.75, height: 0.8, targetHeight: 1.2, fov: 39 },
      rotationTurns: 4.45,
      accent: "#718b9c",
      status: "research-pending",
    },
    {
      id: "sources",
      eyebrow: "07 · procedencia",
      title: "La escena termina en las fuentes",
      body: "Cada capa pública debe poder volver a un registro: quién documentó, qué se observó, cuándo, dónde, bajo qué licencia y con qué límites.",
      layer: "sources",
      sourcePublicIds: [
        asPublicId("source-powo-echinopsis-pachanoi"),
        asPublicId("source-gbif-echinopsis-pachanoi"),
        asPublicId("source-rhs-cacti-succulents-guide"),
      ],
      camera: { distance: 5.1, height: 1.4, targetHeight: 1.1, fov: 40 },
      rotationTurns: 5.4,
      accent: "#496b50",
      status: "published",
    },
  ],
  fallbackText:
    "Esta experiencia visual requiere WebGL. El contenido y sus fuentes continúan disponibles en la ficha de Echinopsis pachanoi.",
} as const satisfies ScrollExperience;
